# Based on Node 10.x LTS image
FROM node:10.15.1-alpine

# Set the default directory where CMD will execute
WORKDIR /app

# Set the default command to execute when creating a new container
CMD ["/bin/bash", "-c", "npm install && npm run dev"]

# Install system requirements
RUN apk add --no-cache build-base python bash asciidoctor


# Convert the readme to html so that it can be shown in the AssignmentPage
COPY README.adoc /
COPY projement/app/README.adoc /FE.adoc
COPY projement/README.adoc /BE.adoc
COPY /projement/app/src/doc.css /doc.css

RUN asciidoctor -a stylesheet=/doc.css /README.adoc --out-file /README.html
RUN asciidoctor -a stylesheet=/doc.css /FE.adoc --out-file /FE.html
RUN asciidoctor -a stylesheet=/doc.css /BE.adoc --out-file /BE.html
