# Development Dockerfile for Django app

FROM python:3.8-slim

# Set the default directory where CMD will execute
WORKDIR /app

# Run Django's runserver by default
CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]

# Define the build argument LIBPQ_DEV with a default value (you can change the default value as needed)
ARG LIBPQ_DEV=0

# Install psycopg2 dependencies based on the value of LIBPQ_DEV
RUN if [ "$LIBPQ_DEV" = "1" ] ; then \
    apt-get update && apt-get install -y libpq-dev \
    ; fi

# Install dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    musl-dev

# Install dependencies from requirements file
COPY projement/requirements.txt .
RUN pip install -r requirements.txt
